import "@/styles/globals.css";
import "@/styles/reset.css";
import type { AppProps } from "next/app";
import Layout from "@/components/layout/Layout";
import { RecoilRoot } from "recoil";
import Modal from "@/components/Modal";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  let childContent: React.ReactNode;
  switch (pageProps.layoutType) {
    case "removeLayout":
      childContent = <Component {...pageProps} />;
      break;
    default:
      childContent = (
        <Layout>
          <Component {...pageProps} />
        </Layout>
      );
      break;
  }

  return (
    <>
      <Head>
        <title>더 줄게 - thejulge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RecoilRoot>
        {childContent}
        <Modal />
      </RecoilRoot>
    </>
  );
}
