import "@/styles/globals.css";
import "@/styles/reset.css";
import type { AppProps } from "next/app";
import Layout from "@/components/layout/Layout";
import { RecoilRoot } from "recoil";
import Modal from "@/components/Modal";
import { ToastProvider } from "@/components/Toast/ToastConenxt";
import { QueryClient, QueryClientProvider } from "react-query";
import Head from "next/head";
import UserInitializer from "@/components/AtomInit";
import { useState } from "react";

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      refetchOnReconnect: false,
      retry: false,
      retryDelay: 3000,
    },
  },
});

export default function App({ Component, pageProps }: AppProps) {
  const [initialized, setInitialized] = useState(false);

  const handleInitialized = () => {
    setInitialized(true);
  };

  let childContent: React.ReactNode;
  switch (pageProps.layoutType) {
    case "removeLayout":
      childContent = <Component {...pageProps} />;
      break;
    default:
      childContent = (
        <Layout>
          <Component {...pageProps} />
        </Layout>
      );
      break;
  }

  return (
    <>
      <Head>
        <title>더 줄게 - thejulge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RecoilRoot>
        <UserInitializer onInitialized={handleInitialized} />
        {initialized ? (
          <ToastProvider>
            <QueryClientProvider client={queryClient}>
              {childContent}
              <Modal />
            </QueryClientProvider>
          </ToastProvider>
        ) : (
          <div>Initializing...</div>
        )}
      </RecoilRoot>
    </>
  );
}
